name: fetch_all_packages
version: 0.0.1
author: Dart Team <misc@dartlang.org>
description: Scrape all dart packages

environment:
  sdk: '>=2.0.0-dev.62.0 <3.0.0'

dependencies:
  http: ^0.12.0
  pool: ^1.4.0